#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "أميال باي — إغلاق حواجز الإنتاج الخمسة"

# ──────────────────────────────────────────────────────────────────────────
# لماذا هذا المرشد موجود
#
# خمسةُ حواجزَ قِيست في تدقيق الجاهزيّة. **ثلاثةٌ منها أُصلحت في الشيفرة**
# (البوّابةُ على الفرع المنشور · حاجزُ APP_DEBUG في الملفّ المُستعمَل ·
# مسبارُ النشر يفحص فعلاً · تمرينُ التعافي يُشغَّل ولا يكذب).
#
# **واثنان لا يستطيعهما إلّا إنسانٌ يملك لوحة Coolify والهاتف** — والباقي
# خطواتُ إثباتٍ لا يصحّ أن يقولها أحدٌ نيابةً عن التجربة.
# ──────────────────────────────────────────────────────────────────────────

# ── ١ ─────────────────────────────────────────────────────────────────────
stage "APP_DEBUG — اقرأ هذا قبل أوّل نشرة"
warn "هذه الخطوةُ تسبق كلَّ شيء: بعد النشرة القادمة، لن تُقلع الحاويةُ إن كان APP_DEBUG=true."
say ""
say "الحاجزُ الجديد في docker/entrypoint.sh يرفض تقديمَ الخدمة والتنقيحُ مفتوح،"
say "لأنّ أثرَ كلّ استثناءٍ يُعرض حينها لأيّ مستخدم: مساراتُ الملفّات، ونصوصُ"
say "الاستعلامات، وأسماءُ الأعمدة. وهي بياناتُ منصّةٍ ماليّة."
say ""
open_url "https://coolify.io/"
step "افتح لوحة Coolify → المشروع → Environment Variables."
step "تأكّد أنّ APP_DEBUG=false (أضِفه إن لم يكن موجوداً)."
step "وتأكّد أنّ APP_ENV=production."
note "وإن كنت تريد التنقيحَ مفتوحاً عن قصدٍ في بيئة تجربة، أضِف AMIAL_ALLOW_DEBUG=true."
if ! confirm "هل APP_DEBUG=false الآن في Coolify؟"; then
  SKIPPED+=("APP_DEBUG=false في Coolify — النشرةُ القادمة لن تُقلع بدونها")
  warn "سُجّلت. لا تنشر قبل ضبطها."
fi

# ── ٢ ─────────────────────────────────────────────────────────────────────
stage "قناةُ الإنذار — الحاجزُ الأخطر"
say "المصالحةُ الليليّةُ تجري ٠٢:٠٠ وتفحص المحافظَ والدفترَ وخزائنَ النقد."
say "وقِيس أنّها **تكتشف الفرقَ فعلاً** ثمّ تحاول الإنذارَ فتجد القائمةَ فارغة،"
say "فتطبع سطراً في ملفٍّ لا يقرؤه أحد. فيبقى الخللُ يتراكم حتّى يشتكي تاجر."
say ""
note "صار الأثرُ يُكتب في مركز الأعطال دائماً — لكنّ ذلك يُرى بفتح اللوحة."
note "والرقمُ أدناه هو ما يجعل الإنذارَ يصلك وأنت نائم."
say ""
step "جهّز رقمَ واتساب يستقبل تنبيهات المنصّة (بصيغة دوليّة، مثال: 967771234567)."
step "أكثرُ من رقم؟ افصل بينها بفاصلة."
ask AMIAL_RECON_ALERT_TO "رقم/أرقام الإنذار:"
if [[ -n "${AMIAL_RECON_ALERT_TO:-}" ]]; then
  write_env AMIAL_RECON_ALERT_TO "$AMIAL_RECON_ALERT_TO"
  step "والآن أضِف المتغيّرَ نفسَه في Coolify → Environment Variables:"
  say "     AMIAL_RECON_ALERT_TO=$AMIAL_RECON_ALERT_TO"
  note "الملفُّ المحلّيُّ لا يصل الخادم — لوحةُ Coolify هي مصدرُ بيئة الإنتاج."
  pause "أضفتَه في Coolify؟ اضغط Enter."
else
  SKIPPED+=("AMIAL_RECON_ALERT_TO — بدونه لا يُعرف فرقٌ ماليٌّ إلّا بفتح اللوحة")
  warn "بلا رقم: ستظهر لافتةٌ حمراءُ دائمةٌ في صفحة صحّة النظام تقول ذلك."
fi

# ── ٣ ─────────────────────────────────────────────────────────────────────
stage "إثباتُ وصول الإنذار — لا يُفترَض"
say "ضبطُ الرقم لا يُثبت وصولَ الرسالة: قد تكون الصيغةُ خاطئة، أو تكون خارجَ"
say "نافذة واتساب (٢٤ ساعة)، أو يكون رمزُ الواجهة منتهياً. **وكلُّها تسقط صامتة.**"
say ""
warn "وقناةُ إنذارٍ لم تُجرَّب ليست قناة — والضبطُ وحدَه يُطمئن ولا يحرس."
say ""
step "على الخادم (Coolify → Terminal، أو ssh):"
say "     php artisan amial:alert-test"
step "ثمّ **افتح الهاتفَ**: لا تكتفِ بأنّ الأمرَ لم يُخرج خطأً."
if confirm "وصلتك رسالةُ الفحص على الهاتف؟"; then
  say "  ✓ القناةُ مُثبتة."
else
  SKIPPED+=("إثباتُ وصول الإنذار — أعِد amial:alert-test حتّى تصل الرسالة فعلاً")
  warn "سُجّلت. راجِع صيغةَ الرقم ورمزَ واجهة واتساب."
fi

# ── ٤ ─────────────────────────────────────────────────────────────────────
stage "فحصُ صحّة النشر — لا يوجد اليوم"
warn "لوحتُك تقول حرفيّاً: Running (no health check)."
say ""
say "أي أنّ Coolify **لا يفحص شيئاً** بعد النشر. فنشرةٌ قاعدتُها ساقطة،"
say "أو هجرتُها لم تبدأ، أو تردّ ٥٠٠ على كلّ طلب — تُقاس «ناجحة» وتحلّ"
say "محلَّ نشرةٍ سليمةٍ كانت تعمل."
say ""
note "والمسبارُ صار مبنيّاً: /railway-health يفحص القاعدةَ والتخزينَ بالعمل،"
note "مع نافذةِ سماحٍ للإقلاع (١٨٠ث) فلا يُسقط نشرةً سليمةً هجرتُها تجري."
note "الناقصُ أن يُوصَل به — وهو ما لا يفعله إلّا أنت."
say ""
step "افتح Coolify → المشروع → Healthcheck (في القائمة اليمنى)."
step "فعّله، واضبط Path = /railway-health"
say "     (أو /health/readiness — كلاهما حقيقيٌّ الآن، والأوّل يحمل نافذةَ السماح)."
step "واضبط Start Period ≥ 180 ثانية — الهجرةُ تجري في الخلفيّة بعد الإقلاع."
step "ثمّ انشر مرّةً وتأكّد أنّ الحالة صارت Running (healthy) لا (no health check)."
if ! confirm "فعّلتَ فحصَ الصحّة وضبطتَ المسار والمهلة؟"; then
  SKIPPED+=("تفعيل Healthcheck في Coolify — بدونه «نجح النشر» لا تعني شيئاً")
fi

# ── ٥ ─────────────────────────────────────────────────────────────────────
stage "نسخةٌ خارج الخادم"
say "النسخةُ المجدولة (٠٣:٠٠) تُكتب في storage/app/backups — **القرصِ نفسِه**."
say "وضياعُ الخادم يعني ضياعَ النسخة معه."
say ""
note "و scripts/backup.sh يدعم الرفعَ إلى S3 أصلاً عبر BACKUP_S3_BUCKET —"
note "الناقصُ الإعدادُ لا الشيفرة."
say ""
step "جهّز دلوَ S3 (أو أيّ خدمةٍ متوافقة) وبيانات aws CLI على الخادم."
ask BACKUP_S3_BUCKET "اسمُ الدلو (اتركه فارغاً لتأجيل هذه الخطوة):"
if [[ -n "${BACKUP_S3_BUCKET:-}" ]]; then
  write_env BACKUP_S3_BUCKET "$BACKUP_S3_BUCKET"
  step "أضِف BACKUP_S3_BUCKET=$BACKUP_S3_BUCKET في Coolify أيضاً."
  step "وتأكّد أنّ aws CLI مُعتمَدٌ على الخادم: aws s3 ls s3://$BACKUP_S3_BUCKET"
  pause "جاهز؟ اضغط Enter."
else
  SKIPPED+=("نسخةٌ خارج الخادم (BACKUP_S3_BUCKET) — حتّى تُضبَط، ضياعُ الخادم = ضياعُ النسخة")
  warn "مؤجَّلة. وهذا قرارٌ مقبولٌ ما دام معلوماً — لا مسكوتاً عنه."
fi

# ── ٦ ─────────────────────────────────────────────────────────────────────
stage "تمرينُ التعافي على الخادم — ورقمُ RTO"
say "جرى التمرينُ محلّيّاً ونجح: قاعدةٌ حُذفت كاملةً واستُعيدت، والبصمةُ متطابقة،"
say "و٥٩٤٦ قيداً عادت في **٣ ثوانٍ**."
say ""
warn "لكنّ ذلك زمنُ هذه الآلة لا زمنَ خادمك. ورقمُ RTO لا يُعرف إلّا بالتجربة."
say ""
step "على الخادم — **وعلى قاعدةٍ جانبيّةٍ لا قاعدة الإنتاج**:"
say "     bash scripts/run_dr.sh"
step "سجّل السطرَ الأخير: «زمن الاستعادة المقيس: N ثانية»."
ask AMIAL_MEASURED_RTO_SECONDS "زمنُ الاستعادة المقيس على الخادم (بالثواني، أو اتركه فارغاً):"
if [[ -n "${AMIAL_MEASURED_RTO_SECONDS:-}" ]]; then
  write_env AMIAL_MEASURED_RTO_SECONDS "$AMIAL_MEASURED_RTO_SECONDS"
  say "  ✓ RTO الحقيقيّ: ${AMIAL_MEASURED_RTO_SECONDS} ثانية."
  note "و RPO الحاليّ = ٢٤ ساعة (النسخةُ ٠٣:٠٠ يوميّاً). إن كان ذلك أكثرَ ممّا"
  note "تقبل خسارته من معاملات، فزِد وتيرةَ النسخ."
else
  SKIPPED+=("تمرينُ التعافي على الخادم — نسخةٌ لم تُستعَد هناك ليست نسخةً هناك")
fi

finish
