#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

banner "أميال باي — إغلاق حواجز الإنتاج قبل تجربة ألفي مستخدم"


# finish — clear, then a closing summary of everything configured.
# ── ٨ ─────────────────────────────────────────────────────────────────────
# **وهذه أوّلُ ما يجب أن يُفعل، لا آخرُه.** وُضعت هنا لأنّ الستَّ قبلها
# إعدادٌ يجب أن يسبق النشرة — لكنّ النشرةَ نفسَها هي الفاصل: كلُّ ما
# أُصلح في الشيفرة **لا يعمل عند أحدٍ حتّى تُضغط**.
stage "قناةُ إيصال رمز التحقّق — الحاجزُ الأوّل"
warn "بلا هذه الخطوة لا يسجّل عميلٌ حقيقيٌّ واحد. وهي تسبق كلَّ ما بعدها."
say ""
say "قِيس أنّ جدول addon_settings **فارغٌ تماماً**، وأنّ لا شيءَ في المشروع"
say "يكتب فيه. وعشرةُ مزوّدين مبنيّون (Meta Cloud · GreenAPI · Twilio …)"
say "**بلا مفتاحٍ يشغّل واحداً منهم** — فكلُّ رقمٍ حقيقيٍّ يُردّ عليه بـ٥٠٣."
say ""
note "وأرقامُ العرض (AMIAL_DEMO_OTP) تعمل بلا قناة — فالتجربةُ الداخليّةُ"
note "لا تكشف هذا العطلَ أبداً. يكشفه أوّلُ عميلٍ حقيقيّ."
say ""
step "اعرِض الحال:  php artisan amial:messaging"
step "اضبط مزوّداً، مثال Meta WhatsApp Cloud:"
say  "     php artisan amial:messaging --set=meta_cloud \\"
say  "       --value=access_token=… --value=phone_number_id=… --enable"
step "**ثمّ أثبِت الوصولَ وافتح الهاتف** (الضبطُ ليس وصولاً):"
say  "     php artisan amial:messaging --test=967xxxxxxxxx"
if ! confirm "أوصلت رسالةُ الاختبار إلى هاتفك فعلاً؟"; then
  SKIPPED+=("قناةُ إيصال رمز التحقّق — بلاها لا يسجّل عميلٌ حقيقيٌّ واحد")
  warn "سُجّلت. التسجيلُ مقفلٌ على غير أرقام العرض حتّى تُضبَط."
fi

# ── ─────────────────────────────────────────────────────────────────────


# ──────────────────────────────────────────────────────────────────────────
# لماذا هذا المرشد موجود
#
# خمسةُ حواجزَ قِيست في تدقيق الجاهزيّة. **ثلاثةٌ منها أُصلحت في الشيفرة**
# (البوّابةُ على الفرع المنشور · حاجزُ APP_DEBUG في الملفّ المُستعمَل ·
# مسبارُ النشر يفحص فعلاً · تمرينُ التعافي يُشغَّل ولا يكذب).
#
# **واثنان لا يستطيعهما إلّا إنسانٌ يملك لوحة Coolify والهاتف** — والباقي
# خطواتُ إثباتٍ لا يصحّ أن يقولها أحدٌ نيابةً عن التجربة.
# ──────────────────────────────────────────────────────────────────────────

# ── ١ ─────────────────────────────────────────────────────────────────────
stage "APP_DEBUG — اقرأ هذا قبل أوّل نشرة"
warn "هذه الخطوةُ تسبق كلَّ شيء: بعد النشرة القادمة، لن تُقلع الحاويةُ إن كان APP_DEBUG=true."
say ""
say "الحاجزُ الجديد في docker/entrypoint.sh يرفض تقديمَ الخدمة والتنقيحُ مفتوح،"
say "لأنّ أثرَ كلّ استثناءٍ يُعرض حينها لأيّ مستخدم: مساراتُ الملفّات، ونصوصُ"
say "الاستعلامات، وأسماءُ الأعمدة. وهي بياناتُ منصّةٍ ماليّة."
say ""
open_url "https://coolify.io/"
step "افتح لوحة Coolify → المشروع → Environment Variables."
step "تأكّد أنّ APP_DEBUG=false (أضِفه إن لم يكن موجوداً)."
step "وتأكّد أنّ APP_ENV=production."
note "وإن كنت تريد التنقيحَ مفتوحاً عن قصدٍ في بيئة تجربة، أضِف AMIAL_ALLOW_DEBUG=true."
if ! confirm "هل APP_DEBUG=false الآن في Coolify؟"; then
  SKIPPED+=("APP_DEBUG=false في Coolify — النشرةُ القادمة لن تُقلع بدونها")
  warn "سُجّلت. لا تنشر قبل ضبطها."
fi


# ── ─────────────────────────────────────────────────────────────────────
stage "النشرُ نفسُه — الدفعُ إلى git لا يَنشُر"
warn "لوحةُ Coolify تقول Source: Manual في النشرات الثلاث الأخيرة."
say ""
say "أي أنّ **لا نشرَ تلقائيّاً**: الدفعُ إلى الفرع لا يُطلق شيئاً. وكلُّ ما"
say "في هذه الجلسة — سقفُ التزامن من ٥ إلى ٢٤، وحدُّ المعدّل الذي كان يردّ"
say "٤٢٩ على ٨٣٪ من الطلبات تحت CGNAT، وقفلُ الدخول المتصاعد، وحدُّ استلام"
say "التاجر، وقفلُ رمز العمليّات — **قائمٌ في المستودع ولا يعمل عند أحد**."
say ""
say "والفرعُ المنشور: claude/project-code-review-yjagv (وقد دُفع إليه)."
say ""
open_url "https://coolify.io/"
step "افتح Coolify → المشروع → تأكّد أنّ الفرع claude/project-code-review-yjagv."
step "اضغط Deploy وانتظر حتّى تنتهي."
note "وستنقطع الخدمةُ أثناءها: اللوحةُ تقول rolling update is not supported —"
note "القديمةُ تُزال قبل أن تعمل الجديدة. مقبولٌ في تجربة، ويُقال لئلّا يُفاجئ."
if ! confirm "هل نُشرت النشرةُ الجديدة ونجحت؟"; then
  SKIPPED+=("النشر — كلُّ إصلاحات الجاهزيّة قائمةٌ في المستودع ولا تعمل عند أحد")
  warn "بدونها لا معنى لأيّ خطوةٍ أخرى: الخادمُ يشغّل الشيفرةَ القديمة."
fi

# ── ٩ ─────────────────────────────────────────────────────────────────────



# ── ١٠ ────────────────────────────────────────────────────────────────────
# **وهذه الخطوةُ هي التي تُجيب السؤالَ فعلاً.** كلُّ قياسٍ حتّى الآن كان
# على `php -S` في حاوية التطوير — والعنقُ الحقيقيُّ سقفُ php-fpm خلف
# nginx على الخادم المنشور، ولم يُقَس قطّ.
stage "قياسُ الطاقة على الخادم الحقيقيّ — الرقمُ الوحيدُ الذي يُجيب"
say "قِيس محلّيّاً ٨٩ طلباً في الثانية، والحدُّ المقدَّر لألفي مستخدمٍ ~٥٠."
say ""
warn "لكنّ ذلك القياسَ **لا يمرّ بـphp-fpm ولا nginx** — وهما العنق."
say ""
say "وسقفُ التزامن كان ٥ في الصورة المنشورة (غيرَ مضبوطٍ إطلاقاً، والافتراضُ"
say "خمسة)، وصار ٢٤. **والرقمُ الحقيقيُّ لا يُعرف إلّا من الخادم نفسِه.**"
say ""
step "من أيّ جهازٍ عليه php وcurl، بعد أن تنجح النشرة:"
say "     BASE=https://amialpay.com php scripts/http-load.php 24 60"
say ""
say "يُخرج: طلباً/ث · وسيطَ الكمون وp95 وp99 · وعددَ الفاشل بأصنافه."
say "ويخرج بصفرٍ إن تجاوز ٥٠ طلباً/ث وكان الفشلُ دونَ ١٪."
say ""
note "وإن جاء دون ٥٠: ارفع pm.max_children في Dockerfile ثمّ أعد النشر —"
note "ولا ترفعه فوق ما تحتمله القاعدة، فـTooManyConnections أسوأ من الانتظار."
if ! confirm "هل قِست الطاقةَ على الخادم الحقيقيّ وتجاوزت ٥٠ طلباً/ث؟"; then
  SKIPPED+=("قياسُ الطاقة على الخادم — «يتحمّل ألفي مستخدم» غيرُ مُثبَتٍ بلا هذا")
  warn "ولا يُقال «جاهز لألفي مستخدم» قبل هذا الرقم. «غير معروف» ليس نجاحاً."
fi



# ── ٩ ─────────────────────────────────────────────────────────────────────
stage "رمزُ دخول الإدارة — إن كان ما زال 1234"
say "رمزُ الحساب الجذر الافتراضيُّ 1234. ومن ملكه ملك اللوحةَ كلَّها:"
say "أرصدةَ العملاء، والتجميدَ، وضبطَ الرسوم، وسجلَّ التدقيق."
say ""
say "والحدُّ على البابِ أُضيف الآن (٦ محاولاتٍ في الدقيقة) — **وحدٌّ على"
say "رمزٍ معروفٍ لا يحمي**: من يعرفه لا يحتاج محاولةً ثانية."
say ""
step "ادخل لوحة الإدارة → تغيير رمز الدخول (admin/auth/change-pin)."
step "اختر أربعةَ أرقامٍ غيرَ متسلسلةٍ ولا متكرّرة (النظام يرفض 1234 و1111 وأمثالها)."
if ! confirm "هل رمزُ الحساب الجذر غيرُ 1234 الآن؟"; then
  SKIPPED+=("رمزُ دخول الإدارة ما زال افتراضيّاً — واللوحةُ كلُّها خلفه")
fi

# ── ١٠ ────────────────────────────────────────────────────────────────────
# **وهذه الخطوةُ هي التي تُجيب السؤالَ فعلاً.** كلُّ قياسٍ حتّى الآن كان
# على `php -S` في حاوية التطوير — والعنقُ الحقيقيُّ سقفُ php-fpm خلف
# nginx على الخادم المنشور، ولم يُقَس قطّ.


# ── ٢ ─────────────────────────────────────────────────────────────────────
stage "قناةُ الإنذار — الحاجزُ الأخطر"
say "المصالحةُ الليليّةُ تجري ٠٢:٠٠ وتفحص المحافظَ والدفترَ وخزائنَ النقد."
say "وقِيس أنّها **تكتشف الفرقَ فعلاً** ثمّ تحاول الإنذارَ فتجد القائمةَ فارغة،"
say "فتطبع سطراً في ملفٍّ لا يقرؤه أحد. فيبقى الخللُ يتراكم حتّى يشتكي تاجر."
say ""
note "صار الأثرُ يُكتب في مركز الأعطال دائماً — لكنّ ذلك يُرى بفتح اللوحة."
note "والرقمُ أدناه هو ما يجعل الإنذارَ يصلك وأنت نائم."
say ""
step "جهّز رقمَ واتساب يستقبل تنبيهات المنصّة (بصيغة دوليّة، مثال: 967771234567)."
step "أكثرُ من رقم؟ افصل بينها بفاصلة."
ask AMIAL_RECON_ALERT_TO "رقم/أرقام الإنذار:"
if [[ -n "${AMIAL_RECON_ALERT_TO:-}" ]]; then
  write_env AMIAL_RECON_ALERT_TO "$AMIAL_RECON_ALERT_TO"
  step "والآن أضِف المتغيّرَ نفسَه في Coolify → Environment Variables:"
  say "     AMIAL_RECON_ALERT_TO=$AMIAL_RECON_ALERT_TO"
  note "الملفُّ المحلّيُّ لا يصل الخادم — لوحةُ Coolify هي مصدرُ بيئة الإنتاج."
  pause "أضفتَه في Coolify؟ اضغط Enter."
else
  SKIPPED+=("AMIAL_RECON_ALERT_TO — بدونه لا يُعرف فرقٌ ماليٌّ إلّا بفتح اللوحة")
  warn "بلا رقم: ستظهر لافتةٌ حمراءُ دائمةٌ في صفحة صحّة النظام تقول ذلك."
fi

# ── ٣ ─────────────────────────────────────────────────────────────────────
stage "إثباتُ وصول الإنذار — لا يُفترَض"
say "ضبطُ الرقم لا يُثبت وصولَ الرسالة: قد تكون الصيغةُ خاطئة، أو تكون خارجَ"
say "نافذة واتساب (٢٤ ساعة)، أو يكون رمزُ الواجهة منتهياً. **وكلُّها تسقط صامتة.**"
say ""
warn "وقناةُ إنذارٍ لم تُجرَّب ليست قناة — والضبطُ وحدَه يُطمئن ولا يحرس."
say ""
step "على الخادم (Coolify → Terminal، أو ssh):"
say "     php artisan amial:alert-test"
step "ثمّ **افتح الهاتفَ**: لا تكتفِ بأنّ الأمرَ لم يُخرج خطأً."
if confirm "وصلتك رسالةُ الفحص على الهاتف؟"; then
  say "  ✓ القناةُ مُثبتة."
else
  SKIPPED+=("إثباتُ وصول الإنذار — أعِد amial:alert-test حتّى تصل الرسالة فعلاً")
  warn "سُجّلت. راجِع صيغةَ الرقم ورمزَ واجهة واتساب."
fi

# ── ٤ ─────────────────────────────────────────────────────────────────────
stage "فحصُ صحّة النشر — الصورةُ تُعلنه الآن، ولم تكن"
say "لوحتُك كانت تقول: Running (no health check) — فكلُّ نشرةٍ «ناجحة»"
say "مهما كانت حالةُ التطبيق: قاعدةٌ ساقطة، أو هجرةٌ لم تبدأ، أو ٥٠٠ على"
say "كلّ طلب. **وقد أُغلق هذا في الشيفرة، فلا يُطلَب منك.**"
say ""
note "الصورةُ المنشورة (Dockerfile) تحمل HEALTHCHECK يسأل /health/readiness —"
note "قاعدةً حيّةً ومهاجراتٍ مكتملةً وتخزيناً يُكتَب فيه. لا /railway-health:"
note "ذاك مسبارُ نشرٍ متسامحٌ بنافذة إقلاع، ومتسامحٌ لا يصلح حارساً دائماً."
note "ويجرّب المنافذَ الثلاثة، فمنفذٌ مكتوبٌ رقماً يجعل الفحصَ يسقط دائماً."
say ""
say "**فما بقي لك اختياريٌّ لا حاجز**: Docker يعرف صحّةَ الحاوية من الصورة،"
say "وضبطُ الحقل في Coolify يجعل Coolify نفسَه **يتصرّف** على أساسه"
say "(إعادةُ تشغيلٍ وإشعار) لا أن يعرضه وحسب."
say ""
step "اختياريّ: Coolify → المشروع → Healthcheck → Path = /health/readiness"
step "واضبط Start Period ≥ 180 ثانية — تُطابق نافذةَ الصورة."
step "وبعد النشرة، تأكّد أنّ الحالة Running (healthy)."
if ! confirm "هل تريد عدَّ هذه مضبوطة؟ (الصورةُ تحرسها في الحالين)"; then
  note "لا بأس — الحاويةُ تُعلن صحّتَها من الصورة، وهذا الحقلُ تحسينٌ لا حاجز."
fi

# ── ٥ ─────────────────────────────────────────────────────────────────────
stage "نسخةٌ خارج الخادم"
say "النسخةُ المجدولة (٠٣:٠٠) تُكتب في storage/app/backups — **القرصِ نفسِه**."
say "وضياعُ الخادم يعني ضياعَ النسخة معه."
say ""
note "و scripts/backup.sh يدعم الرفعَ إلى S3 أصلاً عبر BACKUP_S3_BUCKET —"
note "الناقصُ الإعدادُ لا الشيفرة."
say ""
step "جهّز دلوَ S3 (أو أيّ خدمةٍ متوافقة) وبيانات aws CLI على الخادم."
ask BACKUP_S3_BUCKET "اسمُ الدلو (اتركه فارغاً لتأجيل هذه الخطوة):"
if [[ -n "${BACKUP_S3_BUCKET:-}" ]]; then
  write_env BACKUP_S3_BUCKET "$BACKUP_S3_BUCKET"
  step "أضِف BACKUP_S3_BUCKET=$BACKUP_S3_BUCKET في Coolify أيضاً."
  step "وتأكّد أنّ aws CLI مُعتمَدٌ على الخادم: aws s3 ls s3://$BACKUP_S3_BUCKET"
  pause "جاهز؟ اضغط Enter."
else
  SKIPPED+=("نسخةٌ خارج الخادم (BACKUP_S3_BUCKET) — حتّى تُضبَط، ضياعُ الخادم = ضياعُ النسخة")
  warn "مؤجَّلة. وهذا قرارٌ مقبولٌ ما دام معلوماً — لا مسكوتاً عنه."
fi

# ── ٦ ─────────────────────────────────────────────────────────────────────
stage "تمرينُ التعافي على الخادم — ورقمُ RTO"
say "جرى التمرينُ محلّيّاً ونجح: قاعدةٌ حُذفت كاملةً واستُعيدت، والبصمةُ متطابقة،"
say "و٥٩٤٦ قيداً عادت في **٣ ثوانٍ**."
say ""
warn "لكنّ ذلك زمنُ هذه الآلة لا زمنَ خادمك. ورقمُ RTO لا يُعرف إلّا بالتجربة."
say ""
step "على الخادم — **وعلى قاعدةٍ جانبيّةٍ لا قاعدة الإنتاج**:"
say "     bash scripts/run_dr.sh"
step "سجّل السطرَ الأخير: «زمن الاستعادة المقيس: N ثانية»."
ask AMIAL_MEASURED_RTO_SECONDS "زمنُ الاستعادة المقيس على الخادم (بالثواني، أو اتركه فارغاً):"
if [[ -n "${AMIAL_MEASURED_RTO_SECONDS:-}" ]]; then
  write_env AMIAL_MEASURED_RTO_SECONDS "$AMIAL_MEASURED_RTO_SECONDS"
  say "  ✓ RTO الحقيقيّ: ${AMIAL_MEASURED_RTO_SECONDS} ثانية."
  note "و RPO الحاليّ = ٢٤ ساعة (النسخةُ ٠٣:٠٠ يوميّاً). إن كان ذلك أكثرَ ممّا"
  note "تقبل خسارته من معاملات، فزِد وتيرةَ النسخ."
else
  SKIPPED+=("تمرينُ التعافي على الخادم — نسخةٌ لم تُستعَد هناك ليست نسخةً هناك")
fi

# ── ٧ ─────────────────────────────────────────────────────────────────────
#
# AMIAL-PROD-READINESS-006 — **الخطوةُ التي تُغلق الحلقة.**
#
# الستُّ قبلها إعدادٌ يُضبط مرّةً. وهذه **تُشغَّل بعد كلّ نشرة** — فموضعُها
# هنا ليس لتُفعل اليوم فحسب، بل ليُعرف أنّها موجودة. وسكربتٌ لا يعرف أحدٌ
# بوجوده = سكربتٌ غيرُ مبنيّ (القاعدةُ الثانيةَ عشرة).
stage "فحصُ الدخان — بعد كلّ نشرة، لا مرّةً واحدة"
say "بعد كلّ نشرةٍ اليوم لا يُفحص شيء. ولوحةُ Coolify تقول Running بلا فحصِ صحّة،"
say "فحتّى إقلاعُ الحاوية لا يُتحقَّق منه."
say ""
step "من طرفيّة Coolify (Terminal) بعد أيّ نشرة:"
say "     bash scripts/smoke.sh https://amialpay.com"
say ""
say "سبعةُ فحوص: الجاهزيّةُ الحقيقيّة (قاعدةٌ وتخزينٌ وطابور) · /ping ·"
say "بابُ الإدارة ورمزُ CSRF · الصفحةُ الرئيسة · ترويساتُ الأمان ·"
say "معرِّفُ الطلب · **وأنّ صفحةَ الخطأ لا تُفشي مساراً ولا سرّاً**."
say ""
note "ويخرج بصفرٍ إن سلمت كلُّها — فيصلح خطوةً آليّةً بعد النشر إن أردتَ لاحقاً."
if ! confirm "شغّلتَه مرّةً على النشرة الحاليّة وخرجت كلُّ الفحوص خضراء؟"; then
  SKIPPED+=("فحصُ الدخان بعد النشر (bash scripts/smoke.sh) — نشرةٌ لم تُفحص ليست نشرةً ناجحة")
fi

# ── قبل الختام ────────────────────────────────────────────────────────────
# **ومرشدٌ يُغلق الحواجزَ ولا يقول كيف تُقاس يترك الحكمَ رأياً.**
say ""
say "وبعد كلَّ خطوةٍ من هذه، اقرأ الرقم لا الانطباع:"
say ""
say "    php artisan amial:readiness"
say "    php artisan amial:readiness --base=https://amialpay.com"
say ""
say "كلُّ شرطٍ يُقاس من مصدره، وما لا يُقاس يُقال «غيرُ معروف» ولا يُحسَب"
say "نجاحاً. ويخرج بغير صفرٍ ما دام شرطٌ ساقطاً أو مجهولاً."

finish
